version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: blockchain-metabase
    hostname: metabase
    ports:
      - "3000:3000"
    environment:
      # Database configuration for Metabase application data
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase-data/metabase.db

      # Performance and memory settings
      JAVA_OPTS: "-Xmx1g"

      # Security settings
      MB_PASSWORD_COMPLEXITY: weak
      MB_PASSWORD_LENGTH: 6

      # Site configuration
      MB_SITE_NAME: "Blockchain Test Analytics"
      MB_SITE_URL: "http://localhost:3000"

    volumes:
      # Mount the data directory to access SQLite database
      - "./data:/blockchain-data:ro"

      # Persistent storage for Metabase application data
      - "./metabase-data:/metabase-data"

      # Optional: Mount config directory
      - "./metabase-config:/config"

    restart: unless-stopped

    # Health check to ensure Metabase is ready
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

# Create networks for potential future expansion
networks:
  default:
    name: blockchain-analytics